type=item
items=crossbow
model.crossbow_standby=prestige_electrofield_crossbow
model.crossbow_pulling_0=prestige_electrofield_crossbow_0
model.crossbow_pulling_1=prestige_electrofield_crossbow_1
model.crossbow_pulling_2=prestige_electrofield_crossbow_2
model.crossbow_arrow=prestige_electrofield_crossbow_charged
components.custom_data.weapon=crossbow_3
