type=item
items=crossbow
model.crossbow_standby=electrofield_crossbow
model.crossbow_pulling_0=electrofield_crossbow_0
model.crossbow_pulling_1=electrofield_crossbow_1
model.crossbow_pulling_2=electrofield_crossbow_2
model.crossbow_arrow=electrofield_crossbow_charged
components.custom_data.weapon=crossbow_1
